### ISSUE TITLE
Add all tags to RHS

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/empress-blog-ember-template#10]
### Overview

We are in the process of "Emberifying" the Ember Blog using [empress-blog](https://github.com/empress/empress-blog) and this issue is related to implementing the Ember specific template that makes the new blog look the same as the old one 👍 

If you run this repo locally you will see some example posts, the point of this issue is to make the site look like the existing blog: 

![image](https://user-images.githubusercontent.com/1372946/53520847-7dfb5800-3a8b-11e9-9b28-2465334d418d.png)

### Todo

- [ ] add enough example posts to cover the tags required in the right-hand side of the above screenshot
- [ ] copy the styles so that it has each of the sections available
- [ ] list each of the last 3 posts from the tag under the tag header
  - This will likely require some hacking on [broccoli-static-site-json](https://github.com/empress/broccoli-static-site-json) and it is worth taking to Chris Manson (real_ate) in the #dev-ember-learning channel in Discord

**Comment by amyrlam** [comment]
http://localhost:4200/facey-mc-face (post) - should have 404

http://localhost:4200/tag/facey-mc-face - this works, should be a 404, but tag is not a first class citizen in this system

**Comment by mansona** [comment]
I think all we need to make the http://localhost:4200/facey-mc-face (post) give a 404 is to add an `error.hbs` to the app folder 🤔

**Comment by amyrlam** [comment]
Tags aren't first class citizens, no model for them, but we want to make them real e.g. a Markdown file for each tag, similar to author

**Comment by mansona** [comment]
I think this issue is now out of date for the current implementation of empress-blog 👍
